#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Script and tools options may have been tweaked by me.
#
#Numbers the lines in the selection.

echo -n "$KKEDIT_SELECTION" | sed '/^\s*$/d' | sed '=' | sed '{N;s/\n/\t/}'
