#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Script and tools options may have been tweaked by me.
#
#Removes line numbering in the selection.

echo -n "$KKEDIT_SELECTION" | sed 's/^[0-9][0-9]*\t//g'
