#!/bin/bash -e

#©keithhedger Fri 3 Oct 17:38:03 BST 2014 kdhedger68713@gmail.com

MAKEPOS=0
MAKEMOS=0
DOMAINNAME=kkedit

if [ "X$1" = "Xmakepos" ];then
	MAKEPOS=1
	MAKEMOS=0
fi

if [ "X$1" = "Xmakemos" ];then
	MAKEPOS=0
	MAKEMOS=1
fi

langs="fr_FR"
if [ -e ${DOMAINNAME}.pot ];then
	xgettext --package-name  ${DOMAINNAME}  --package-version 1.2  --join-existing --default-domain  ${DOMAINNAME} --output ${DOMAINNAME}.pot KKEdit/src/*.cpp
else
	xgettext --package-name  ${DOMAINNAME}  --package-version 1.2 --default-domain  ${DOMAINNAME} --output ${DOMAINNAME}.pot KKEdit/src/*.cpp
fi

for arg in $langs
	do
		mkdir --parents po/${arg}/LC_MESSAGES
		if [ $MAKEPOS -eq 1 ];then
			msginit --no-translator --locale $arg --output-file ${arg}.po --input ${DOMAINNAME}.pot
		fi
		if [ $MAKEMOS -eq 1 ];then
			msgfmt --check --verbose --output-file po/${arg}/LC_MESSAGES/${DOMAINNAME}.mo ${arg}.po
		fi
	done