#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

VERSION=$(head ./configure.ac|grep AC_INIT|awk -F [ '{print $3}'|awk -F ] '{print $1}')

svn commit -m ""
cd /tmp
svn co file:///media/LinuxData/Development/SVN/KKEdit
find KKEdit -name ".svn" -exec rm -r '{}' \; || true
rm /tmp/KKEdit/makepkg
rm /tmp/KKEdit/KKEdit.LFSBuild
rm -r /tmp/KKEdit/artwork
mv /tmp/KKEdit /tmp/KKEdit-${VERSION}

cd /tmp/KKEdit-${VERSION}

./remakesourcelist
aclocal
autoheader
touch NEWS README AUTHORS
automake --add-missing --copy
autoconf
rm -rf ./autom4te.cache
rm ./compile ./missing ./COPYING ./AUTHORS ./NEWS
cd ..
tar -czvhf KKEdit-${VERSION}.tar.gz KKEdit-${VERSION}
rm -r /tmp/KKEdit-${VERSION}
