#!/bin/bash -e

#©keithhedger Thu 5 Sep 13:39:19 BST 2013 kdhedger68713@gmail.com

if [ "${KKEDIT_SELECTION:0:1}" != "#" ];then
	while read
		do
			echo "#${REPLY}"
		done < <(echo -n "${KKEDIT_SELECTION}")
else
	while read
		do
			if [ ${REPLY:0:1} = "#" ];then
				echo "${REPLY#"#"}"
			else
				echo $REPLY
			fi
		done < <(echo -en "${KKEDIT_SELECTION}")
fi 
