#!/bin/bash -e

#©keithhedger Thu 2 May 11:16:53 BST 2013 kdhedger68713@gmail.com

cd "$KKEDIT_CURRENTDIR"

if [ X$1 == "Xroot" ];then
	sudo ./"$(basename "$KKEDIT_CURRENTFILE")"
else
	./"$(basename "$KKEDIT_CURRENTFILE")"
fi