#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

make clean ||true

VERSION=$(head ./configure.ac|grep AC_INIT|awk -F [ '{print $3}'|awk -F ] '{print $1}')

svn commit -m ""
cd /tmp
svn co file:///media/LinuxData/Development/SVN/KKEdit/qtbranch KKEditQT
find KKEditQT -name ".svn" -exec rm -r '{}' \; || true
rm /tmp/KKEditQT/makepkg
rm /tmp/KKEditQT/KKEdit.LFSBuild
rm -r /tmp/KKEditQT/artwork
mv /tmp/KKEditQT /tmp/KKEditQT-${VERSION}

cd /tmp/KKEditQT-${VERSION}
./autogen.sh --prefix=/usr
make clean
make distclean
cd ..
tar -czvhf KKEditQT-${VERSION}.tar.gz KKEditQT-${VERSION}
rm -r /tmp/KKEditQT-${VERSION}
