#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Tweaked by me.

echo -n "$KKEDIT_SELECTION"|sed -e '/^\s*$/d'

#Original script:
#echo -n "$KKEDIT_SELECTION"|sed -e '/^\s*$/d'
