#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Tweaked by me.

echo -n "$KKEDIT_SELECTION"|sed -e 's/\&nbsp;/ /g' -e 's/\s\s\s*/ /g' -e 's/\s\s*$//g' -e 's/^\s\s*//g'

#Original script:
#echo -n "$KKEDIT_SELECTION"|sed -e 's/\&nbsp;/ /g' -e 's/\s\s\s*/ /g' -e 's/\s\s*$//g' -e 's/^\s\s*//g'
