#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Script and tools options may have been tweaked by me.
#
#Removes comment '#' from start of selection.

echo -n "$KKEDIT_SELECTION"|sed -e 's/^\s*#\s*//g'

#Original script:
#echo -n "$KKEDIT_SELECTION"|sed -e 's/^\s*#\s*//g'
