#!/bin/bash -e

#©keithhedger Sat 8 Oct 17:07:10 BST 2016 kdhedger68713@gmail.com

KKEDIT=../../app/kkedit
KKMSG=../../app/kkeditmsg
INSTANCE=12345

#if arg then remove and flush q then exit
if [ "X$1" != "X" ];then
	$KKMSG -k $INSTANCE -fR
	exit 0
fi
#make sure queue is empty
$KKMSG -k $INSTANCE -f

#open instance or bring to front
($KKEDIT -i $INSTANCE) &

#open session 2
#restore from session file
#$KKMSG -k $INSTANCE -s "RestoreSession:${HOME}/.KKEdit/plugins-gtk/session-2" -a
#restore via session menu
$KKMSG -k $INSTANCE -s "ActivateMenuNamed:2-RestoreSession" -a
