#!/bin/bash -e

#©keithhedger Thu 5 Sep 13:39:19 BST 2013 kdhedger68713@gmail.com

tfile=/tmp/data$$
:>$tfile
echo -n "${KKEDIT_SELECTION}" > $tfile

case $KKEDIT_SOURCE_LANG in
	"sh" | "Python" | "Makefile" | ".desktop" | "Perl")
		COMMENTCHARS="#"
		COMMENTLEN=1
		if [ "X${KKEDIT_SELECTION:0:$COMMENTLEN}" = "X${COMMENTCHARS}" ];then
			sed -i "s/^${COMMENTCHARS}\(.*\)/\1/g" $tfile
		else
			sed -i "s/\(.*\)/${COMMENTCHARS}\1/g" $tfile
		fi
		;;

	"C++" | "C" | "Objective-C" | "C/C++/ObjC Header" | "Java" | "Pascal")
		COMMENTCHARS='//'
		COMMENTLEN=2
		if [ "X${KKEDIT_SELECTION:0:$COMMENTLEN}" = "X${COMMENTCHARS}" ];then
			sed -i "s@^${COMMENTCHARS}\(.*\)@\1@g" $tfile
		else
			sed -i "s@\(.*\)@${COMMENTCHARS}\1@g" $tfile
		fi
		;;

	"HTML")
		COMMENTCHARS='<!--'
		COMMENTLEN=4
		if [ "X${KKEDIT_SELECTION:0:$COMMENTLEN}" = "X${COMMENTCHARS}" ];then
			sed -i 's/^<!--\(.*\)-->$/\1/g' $tfile
		else
			sed -i 's/\(.*\)/<!--\1-->/g' $tfile
		fi
		;;

	*)
		echo -n "${KKEDIT_SELECTION}"
		exit 0
		;;
esac

cat $tfile
rm $tfile
